name: Deploy Vue App
on:
  push:
    branches: [ main ] # 當您推送到 main 時自動觸發
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          cd client
          npm install
          npm run build
          cd ..
          cd server
          npm install
          npm start
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist # 這裡是指向編譯後的資料夾